name: Deployment on development
on:
    push:
        branches:
            - '*'

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
                              
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/facepass-frontend-general:latest
                  context: .

    deploy-to-aws:
        needs: build
        runs-on: ubuntu-latest
        env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Copy file via ssh password
              uses: appleboy/scp-action@v0.1.3
              with:
                  host: ${{ secrets.HOST_SERVER }}
                  username: ${{ secrets.HOST_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATEKEY }}
                  port: 22
                  source: 'docker-compose.yml'
                  target: '/home/action/facepass-frontend-general'
            - name: docker compose
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST_SERVER }}
                  username: ${{ secrets.HOST_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATEKEY }}
                  port: 22
                  script: |
                      export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
                      cd /home/action/facepass-frontend-general
                      echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
                      docker compose down
                      docker compose pull
                      docker compose up -d
                      rm -rf /home/action/facepass-frontend-general